workflows:
  my-voca-app-ios:
    name: My Voca App iOS Build
    instance_type: mac_mini_m2
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Add iOS platform
        script: |
          npx cap add ios
          npx cap sync ios
      - name: Build iOS App (Unsigned)
        script: |
          cd ios/App
          xcodebuild build -workspace App.xcworkspace -scheme App -destination generic/platform=iOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - /Users/builder/clone/ios/App/build/Release-iphoneos/*.app